version: "0"
services:
  react:
    build:
      context: ./EarthlyTeaTales/ #move to the root of folder struct
      dockerfile: Dockerfile
    image: react-earthly-tea-tales-frontend-image
    container_name: react-earthly-tea-tales-frontend-container
    volumes:
      - ./EarthlyTeaTales:/usr/src/app/EarthlyTeaTales
      - /usr/src/app/EarthlyTeaTales/node_modules
    ports:
      - "5173:5173" #for docker to know where to redirect hot module reload queries
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  post-gres-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=earthlyteatalesdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - post-gres-db:/var/lib/postgresql/data
volumes:
  post-gres-db:
    driver: local
