version: "0"
services:
  post-gres-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - post-gres-db:/var/lib/postgresql/data
volumes:
  post-gres-db:
    driver: local
